evolving: true
nb_mpi_processes: 4

population_size: 4
nb_elapsed_generations: 0
nb_generations: 10

save_frequency: 0
wandb_logging: false

env_path: envs.score.control
task: acrobot
seeding: reg
nb_steps: inf

algorithm: ga
bots_path: bots.static.control

transfer: none
merge: none
recurrent: none
sigma: none

dir1: ${env_path}~${task}~${seeding}~${nb_steps}
dir2: ${algorithm}~${bots_path}
dir3: ${hydra.job.override_dirname}
dir4: ${hydra.job.override_dirname}
dir5: ${population_size}

full_dir: ${dir1}/${dir2}/${dir3}/${dir4}/${dir5} 

hydra:
  run:
    dir: data/outputs/${full_dir}/
  sweep:
    dir: data/outputs/
    subdir: ${full_dir}/
  job:
    config:
      override_dirname:
        exclude_keys:

          - evolving
          - nb_mpi_processes

          - population_size
          - nb_elapsed_generations
          - nb_generations

          - save_frequency
          - wandb_logging

          - env_path
          - task
          - seeding
          - nb_steps

          - algorithm
          - bots_path
