pop_size: 4
prev_num_gens: 0
num_gens: 5

save_frequency: 0

space_path: gran.nevo.space.reinforcement.gym_fb_control
task: cart_pole
seed: scheduled
num_steps: infinite

alg: ga
agent_path: gran.nevo.agent.static.gym_fb_control

transfer: none
merge: False
net_recurrence: False
net_sigma: 0.01

num_tests: 1
num_steps_per_test: 1000000

# task=cart_pole,seed=scheduled/ae=vae~beta.../ar.mdnrnn~.../

# dir1: task & details
# cart_pole, seed, num_steps
# dir2: autoencoder & autoregressor
# dir3: agent learning: ne, es, ac, ar
# dir4: 
dir1: ${env_path}~${task}~${seed}~${num_steps}
dir2: ${alg}~${agent_path}
dir3: ${hydra.job.override_dirname}
dir4: ${pop_size}

full_dir: ${dir1}/${dir2}/${dir3}/${dir4}

hydra:
  run:
    dir: data/outputs/${full_dir}/
  sweep:
    dir: data/outputs/
    subdir: ${full_dir}/
  job:
    config:
      override_dirname:
        exclude_keys:

          - stage
          - num_mpi_procs

          - pop_size
          - prev_num_gens
          - num_gens

          - save_frequency
          - wandb_logging

          - env_path
          - task
          - seed
          - num_steps

          - alg
          - agent_path

          - num_tests
          - num_steps_per_test

          - launcher