name: neuroevolution

# Agent evolution algorithm
algorithm: ga # ga | es 
pop_size: 40
num_gens_per_iter: 100

# Agent evolution details
run_num_steps: infinite # integer | infinite
gen_transfer: no # no | fit | env+fit | env+mem+fit
pop_merge: no # no | yes

# Agent network
net:
  type: dynamic
  recurrent: true

sigma:
  value: 0.01
  is_adaptive: true

# Training
save_interval: 1

# Testing
num_tests: 10
num_steps_per_test: infinite

# Save directory
dir: "algorithm=${.algorithm},\
     pop_size=${.pop_size},\
     net_type=${.net.type},\
     run_num_steps=${.run_num_steps},\
     gen_transfer=${.gen_transfer},\
     pop_merge=${.pop_merge}"