defaults:
  - autoencoder: none
  - autoregressor: none
  - ecosystem: neuroevolution
  - _self_

# Experiment
stage: train # train | test
task: cart_pole
mode: reinforcement # reinforcement | imitation
num_iters: 1

# Hardware requirements
num_cpus: 4
num_gpus: 0

# Wandb
wandb:
  mode: disabled # disabled | online | offline
  project: gran

# Directory management
dir: task=${task},mode=${mode}
full_dir: ${dir}/${autoencoder.dir}/${autoregressor.dir}/${ecosystem.dir}

hydra:
  job:
    chdir: true
  run:
    dir: data/outputs/agent-based/${full_dir}/
  sweep:
    dir: data/outputs/agent-based/
    subdir: ${full_dir}/