# Subconfigs
defaults:
  - agent: neuroevolution
  - autoencoder: none
  - autoregressor: none
  - _self_

# Experiment
stage: train # train | test
env: cart_pole
paradigm: reinforcement
num_iters: 1

# Collection
collection_episodes: 400

# Hardware requirements
num_cpus: 4
num_gpus: 0

# W&B
wandb: disabled # disabled | online | offline

# Directory management
dir: env.${env}~paradigm.${paradigm}
full_dir: ${dir}/agent-${agent.dir}/autoencoder-${autoencoder.dir}/autoregressor-${autoregressor.dir}/

hydra:
  job:
    chdir: true
  run:
    dir: data/outputs/agent/${full_dir}/
  sweep:
    dir: data/outputs/agent/
    subdir: ${full_dir}/