rands:
  nb_mpi_processes: 4
  env_path: envs.cpu.score.control
  env:
    task: acrobot
    transfer: none
    trials: 1
    steps: 0
    seeding: 0
  bots_path: bots.cpu.static.control
  bots:
    static:
      recurrent: false
      sigma: 0.01
  population_size: 16
  nb_generations: 10
  merge: false
  save_frequency: 0
  wandb_logging: false
hydra:
  launcher:
    account: rrg-pbellec
    cpus_per_task: ${rands.nb_mpi_processes}
  run:
    dir: data/logs/${hydra.job.override_dirname}/
  sweep:
    dir: data/logs/
    subdir: ${hydra.job.override_dirname}