rands:
  nb_mpi_processes: 4
  env:
    _target_: gran.rands.envs.cpu.score.control
    task: ???
    transfer: ???
    trials: 1
    steps: ???
    seeding: 0
  bots_path: bots.cpu.static.control
  bots:
    static:
      recurrent: ???
      sigma: 0.01
  population_size: 16
  nb_elapsed_generations: 0
  nb_generations: 10
  merge: false
  save_frequency: 0
  wandb_logging: false
hydra:
  run:
    dir: data/logs/${hydra.job.override_dirname},/
  sweep:
    dir: data/logs/
    subdir: ${hydra.job.override_dirname},/
  job:
    config:
      override_dirname:
        exclude_keys:
          - launcher
          - nb_mpi_processes