stage: train
num_mpi_procs: 4

pop_size: 4
prev_num_gens: 0
num_gens: 5

save_frequency: 0
wandb_logging: false

wandb:
  mode: online
  project: test

env_path: env.score.gym_state_control
task: cart_pole
seed: -1
num_steps: -1

alg: ga
bot_path: bot.static.control

transfer: none
merge: False
recurrent: False
sigma: 0.01

num_tests: 1
num_steps_per_test: 1000000

dir1: ${env_path}~${task}~${seed}~${num_steps}
dir2: ${alg}~${bot_path}
dir3: ${hydra.job.override_dirname}
dir4: ${pop_size}

full_dir: ${dir1}/${dir2}/${dir3}/${dir4}

hydra:
  run:
    dir: data/outputs/${full_dir}/
  sweep:
    dir: data/outputs/
    subdir: ${full_dir}/
  job:
    config:
      override_dirname:
        exclude_keys:

          - stage
          - num_mpi_procs

          - pop_size
          - prev_num_gens
          - num_gens

          - save_frequency
          - wandb_logging

          - env_path
          - task
          - seed
          - num_steps

          - alg
          - bot_path

          - num_tests
          - num_steps_per_test

          - launcher