task: cart_pole
beta: 0.25

encoder:
  hidden_size: 100
  latent_size: 100

predictor:
  num_features: 4
  num_actions: 2
  hidden_size: 100
  num_gaussians: 5
  predicting_reward: False
  predicting_termination: False 